#server:
#  port: 8080
#spring:
#  #数据库连接配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mywork?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: dzm19961023
#
##mybatis的相关配置
#mybatis:
#  #mapper配置文件
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.example.springdemo.entity
#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true